### PR TITLE
Adding python proxy server to samples

### PR DESCRIPTION
**Pull request by JenMadiedo**
Issue Number: 269

## Summary
Adding the simple python proxy server to the samples repository so it can be used to test the sdk proxy connection locally

## Changes

- Adding samples/python-proxy-server

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] This is not a breaking change. If it is, please describe it below.

## Is this a breaking change?
If yes, what workflow does this break? 

## Anything else?
Other comments, collaborators, etc.
This PR Closes Issue #

### CODE REVIEW

**Review by juzuluag — APPROVED** [review]
Awesome. Thanks for doing this. 🚢

**Review by bderusha — COMMENTED** [review]
Is there a specific reason to have custom code here?  The code itself likely does the job, but I am a little concerned about maintenance, and generally being able to discern between "real" app-to-proxy config issues and potential bugs in untested code.

As this is sample code which no one is obligated to run in their setup, I don't think it's worth blocking the PR, but I would be interested to know if we investigated just running opensource proxies like NGINX or HAproxy from their published docker images

**Comment by juzuluag** [comment]
> Is there a specific reason to have custom code here? The code itself likely does the job, but I am a little concerned about maintenance, and generally being able to discern between "real" app-to-proxy config issues and potential bugs in untested code.
> 
> As this is sample code which no one is obligated to run in their setup, I don't think it's worth blocking the PR, but I would be interested to know if we investigated just running opensource proxies like NGINX or HAproxy from their published docker images

Hi @bderusha , thank you for looking into this. We looked into [squid](https://github.com/sameersbn/docker-squid) and it can be used as well. This one implementation is mainly to have some control over, and yes, it could be more 'tech-debt' for the repo, but at least it is an easy way to test the request. @JenMadiedo might have more insights too.

**Review by rakker91 — APPROVED** [review]

**Comment by JenMadiedo** [comment]
> > Is there a specific reason to have custom code here? The code itself likely does the job, but I am a little concerned about maintenance, and generally being able to discern between "real" app-to-proxy config issues and potential bugs in untested code.
> > As this is sample code which no one is obligated to run in their setup, I don't think it's worth blocking the PR, but I would be interested to know if we investigated just running opensource proxies like NGINX or HAproxy from their published docker images
> 
> Hi @bderusha , thank you for looking into this. We looked into [squid](https://github.com/sameersbn/docker-squid) and it can be used as well. This one implementation is mainly to have some control over, and yes, it could be more 'tech-debt' for the repo, but at least it is an easy way to test the request. @JenMadiedo might have more insights too.

Resolved offline with Bill, will add a note to the readme that python proxy is a very simple sample and other more complex ones could be used if needed

**Pull request merged**
