### PR TITLE
ADR 0004: Documentation

### PR DESCRIPTION
**Pull request by bderusha**
Issue Number: 446

## Summary
Introduces ADR 0004 to standardize documentation.

### CODE REVIEW

**Review by gfmatthews — APPROVED** [review]
Structure overall looks good. No issues from my side. Of particular interest to me are the "as-is" usage docs as that's the way we can encourage new users to get involve with the project. I know the inner detail of those is outside the scope of this proposal but I'm happy to assist with that when we get to that stage.

**Review by esgraham — APPROVED** [review]
Propose changes look good.  We will want to ensure that the changes do not conflict with https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/99

**Comment by bderusha** [comment]
> Propose changes look good. We will want to ensure that the changes do not conflict with [Green-Software-Foundation#99](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/99)

@esgraham Good call!  Seems like it is fully aligned with this proposal.  This would take that PR further.

**Comment by bderusha** [comment]
Closing in favor of having this conversation on the main GSF repo Green-Software-Foundation/carbon-aware-sdk#105

**Pull request closed without merging**
