### PR TITLE
Rearranging test and src folder structure

### PR DESCRIPTION
**Pull request by JenMadiedo**
Issue Number: (Link to Github Issue or Azure Dev Ops Task/Story)

## Summary
Re-arranging folder structure to better match dotnet standards. Is up to date with latest dev as of 06-06-2022T18:00:00.

Includes
1. Arranging each project to have a `src` and `tests` directory as needed
3. Arranging folder hierarchy to match file flow
4. collapsing dotnet directory

Example:
src/
|---CarbonAware/
| |-------src/
| |-------tests/
|---CarbonAware.WebApi/
| |-------src/
| |-------tests/
etc

## Changes

- No logic changes, strictly folder restructure

## Checklist

- [X] Local Tests Passing?
- [X] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [X] This is not a breaking change. If it is, please describe it below.

## Is this a breaking change?
Yes. This changes the location of folders and their references in the .csproj files and in the .sln file so after merging, everyone will need to pull and merge into their current branches.

## Anything else?
Other comments, collaborators, etc.
This PR Closes Issue #

### CODE REVIEW

**Review by juzuluag — COMMENTED** [review]
@JenMadiedo, I though we were going to leave `src/dotnet` as a reference for future supported languages (i.e `src/python, src/java`)

**Comment by JenMadiedo** [comment]
> @JenMadiedo, I though we were going to leave `src/dotnet` as a reference for future supported languages (i.e `src/python, src/java`)

It was my impression that the plan of eventually expanding this to other languages/platforms is no longer actually the plan so it could be safely removed. I could be wrong/over-zealous in my collapsing. @bderusha  do you know if ^^ came from a conversation with Vaughn or if it's just the sense we've gotten

**Comment by bderusha** [comment]
> > @JenMadiedo, I though we were going to leave `src/dotnet` as a reference for future supported languages (i.e `src/python, src/java`)
> 
> @juzuluag It was my impression that the plan of eventually expanding this to other languages/platforms is no longer actually the plan so it could be safely removed. I could be wrong/over-zealous in my collapsing. @bderusha do you know if ^^ came from a conversation with Vaughn or if it's just the sense we've gotten

That information is based on my last conversation with Vaughan, but I do think it would behoove us to check in with him on the impact of altering the directory structure for the project broadly.

**Comment by gfmatthews** [comment]
Humblest of humble suggestions: Mark this as a draft for the moment while we're still figuring out when to perform this giant merge :)

**Comment by JenMadiedo** [comment]
> Humblest of humble suggestions: Mark this as a draft for the moment while we're still figuring out when to perform this giant merge :)

Whoops, meant to keep it in draft, thanks

**Review by bderusha — APPROVED** [review]
This makes me so happy :shipit:

**Review by pritipath — APPROVED** [review]

**Pull request merged**
